name: "Pull Request Labeler"
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
          
